"""Run the content-review sample cases against the REAL model, batched to save quota.

One model call is made per group (A, B, C by default = 3 calls). Nothing here is run by pytest.

    .venv/bin/python scripts/run_live_cases.py --dry-run               # show the documents, no calls
    .venv/bin/python scripts/run_live_cases.py --yes                   # groups A, B, C -> 3 calls
    .venv/bin/python scripts/run_live_cases.py --yes --group A --model gemini-3.8-flash
    .venv/bin/python scripts/run_live_cases.py --print-docs            # write docs/content-review-test-cases.md
"""

import argparse
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests" / "cases"))

import support  # noqa: E402

SEPARATOR = "\n\n"
DOCS_FILE = ROOT / "docs" / "content-review-test-cases.md"


def build_documents(cases: list[dict], groups: list[str]):
    """Return {group: (document, [(case, start, end)])}; cases of a group share one model call."""
    documents = {}
    for group in groups:
        members = [case for case in cases if case["group"] == group]
        if not members:
            continue
        text, spans = "", []
        for case in members:
            if text:
                text += SEPARATOR
            spans.append((case, len(text), len(text) + len(case["content"])))
            text += case["content"]
        documents[group] = (text, spans)
    return documents


def write_docs(cases: list[dict]) -> None:
    lines = [
        "# Content review: sample content and expected results",
        "",
        "Generated by `python scripts/run_live_cases.py --print-docs` from `tests/cases/content_review_cases.json`. Do not edit by hand.",
        "Paste each sample into the UI on its own. Acronyms are flagged once per document, so test them separately.",
        "",
    ]
    for group in sorted({c["group"] for c in cases}):
        lines += [f"## Group {group}", "", "| Id | Scenario | Sample content | Expected |", "|---|---|---|---|"]
        for case in (c for c in cases if c["group"] == group):
            expected = []
            for want in case.get("expect", []):
                original = " / ".join(support.as_list(want["original"]))
                fix = f" -> {want['improved']}" if "improved" in want else ""
                expected.append(f"`{original}`{fix} ({'/'.join(support.as_list(want.get('types', [])))})")
            for wanted in case.get("expect_types", []):
                expected.append("an issue of type " + "/".join(support.as_list(wanted)))
            expected += [f"must NOT flag `{f}`" for f in case.get("forbid", [])]
            if case.get("exact_count") == 0:
                expected.append("no issues")
            elif "exact_count" in case:
                expected.append(f"exactly {case['exact_count']} issue(s)")
            if "min_issues" in case:
                expected.append(f"at least {case['min_issues']} issues")
            if case.get("source") == "dictionary":
                expected.append("(from resources/deprecated_terms.xlsx)")
            content = case["content"].replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {case['id']} | {case['scenario']} | `{content}` | {'<br>'.join(expected) or '-'} |")
        lines.append("")
    DOCS_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {DOCS_FILE}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--group", action="append", help="A, B, C or D (repeatable). Default: A B C")
    parser.add_argument("--model", help="Gemini model id (default: GEMINI_MODEL)")
    parser.add_argument("--yes", action="store_true", help="Confirm that real model calls (and quota) may be used")
    parser.add_argument("--dry-run", action="store_true", help="Print the batched documents and call count only")
    parser.add_argument("--print-docs", action="store_true", help="Write docs/content-review-test-cases.md and exit")
    args = parser.parse_args()

    cases = support.load_cases()
    if args.print_docs:
        write_docs(cases)
        return 0

    documents = build_documents(cases, args.group or ["A", "B", "C"])
    print(f"{len(documents)} model call(s) would be made (one per group): {', '.join(documents)}")
    if args.dry_run:
        for group, (text, spans) in documents.items():
            print(f"\n--- group {group}: {len(spans)} cases, {len(text)} characters ---\n{text}")
        return 0
    if not args.yes:
        print("Refusing to call the model without --yes (the free tier allows ~20 calls/day/model).")
        return 2

    from app.config import get_settings
    from app.errors import ProviderRateLimited, ServiceError
    from app.llm.gemini_provider import GeminiProvider
    from app.schemas.content_review import ReviewRequest
    from app.services.content_review_service import ContentReviewService, locate_issue
    from app.services.deprecated_terms import DeprecatedTerms

    settings = get_settings()
    service = ContentReviewService(
        GeminiProvider(settings),
        settings.max_review_content_chars,
        deprecated_terms=DeprecatedTerms(settings.deprecated_terms_file),
    )
    passed = failed = calls = 0
    for group, (text, spans) in documents.items():
        language = spans[0][0].get("language", "en")
        print(f"\n=== Group {group} ({len(spans)} cases) ===")
        started = time.monotonic()
        try:
            calls += 1
            response = service.review(ReviewRequest(requestId=f"live-{group}", content=text, language=language, model=args.model))
        except ProviderRateLimited as exc:
            print(f"Quota exhausted: {exc.message}\ndetails: {exc.details}")
            break
        except ServiceError as exc:
            print(f"Call failed: {exc.code}: {exc.message}")
            failed += len(spans)
            continue
        print(f"model call took {time.monotonic() - started:.1f}s, {len(response.issues)} issues returned")
        located = [(locate_issue(text, issue), issue) for issue in response.issues]
        for case, start, end in spans:
            mine = [
                (issue.original, issue.improved, issue.issueType.value)
                for position, issue in located
                if position is not None and start <= position < end
            ]
            problems = support.evaluate_case(case, mine)
            status = "PASS" if not problems else "FAIL"
            passed, failed = passed + (not problems), failed + bool(problems)
            print(f"[{status}] {case['id']}: {case['scenario']}")
            if problems:
                print(f"       got: {mine}")
                for problem in problems:
                    print(f"       - {problem}")
    print(f"\nSummary: {passed} passed, {failed} failed, {calls} model call(s) made, model={args.model or settings.gemini_model}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
